# Generated by Django 3.2.9 on 2021-11-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_salesdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesData',
        ),
    ]
